### PR TITLE
Script RBAC - new system (but works for all reads)

### PR DESCRIPTION
**Pull request by Ryan2065**
So I was researching row level security and other things like that, and came across Entity Framework Core's implementation of this as filters.

You can set a global filter on a table and it's auto-applied to all queries. On top of that, the filter can use data (like user Id) to essentially add row level security easily to all EF queries. This PR implements that in a repeatable way on Script so we can easily do it for anything else.

A few views were added, but the money view is v_RBACScriptToObjectId - this view shows all SIDs / AAD Object Ids that have access to scripts based on our RBAC model. 

Then, the IHTTPContextAccessor was added to the dbContext so it knew what we're auth'ed as. I originally was going to send it an IUser or something, but I can't send the DBContext anything that has the DbContext as a param because of recursive issues - so I decided to just have the logic to get the user SID / group SIDs in the DbContext. Anyway, from the IHTTPContextAccessor I can get the user authed and their group sids and then pass that to the model builder with this line:

```
modelBuilder.ApplyConfiguration(new VRBACScriptToObjectIdConfiguration(this));
```

now the model builder gets the DbContext and can get the user object ids. 

I'll expand this out to Jobs, Variables, ScriptVersion, and Roles.

This closes the loop of auto-security. I had decent automated security for edits (based off object id) but not for gets. Now this, in combination with the AuthorizationFilter (which I'll disable for reads) should keep everything secure. Only time we'll need to manually check is on bulk endpoints.

### CODE REVIEW

**Comment by fredbainbridge** [comment]
I am getting a 404 on the script controller now.  Job controller still works.  I confirmed master still works.  

to repo:  
```
 New-EAScript -Name 'test11' -Description 'test' -Body $body -Server localhost -Port 5001
```

**Comment by Ryan2065** [comment]
Here's what I get when I try to use the module:

```
PS C:\Users\Ryan2\Dropbox\Code\Automation> New-EAScript -Name 'test11' -Description 'test' -Body $body -Server localhost -Port 44354
New-EAScript: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```

My testing was done with the Tests\_RunTests.ps1 script after turning on windows auth.

How are you handling auth? This PR practically requires authorization either through AAD or Windows. I always manually turn on Windows auth and remove anonymous since I figure you're doing something with AAD.

image

**Comment by Ryan2065** [comment]
Also the current Windows user (even if it's a workgroup) should always be a full admin. this code block is in the Startup of the web server:

```
            // Add current user to full admin role
            var vUser = user.RegisterCurrent();
            if (!_context.RoleMembershipUser.Where(p => p.UserId == vUser.UserId && p.Role.Name.Equals("Administrators")).Any())
            {
                var admin = _context.Role.Where(p => p.Name.Equals("Administrators")).FirstOrDefault();
                var newRoleMembership = new RoleMembershipUser();
                newRoleMembership.RoleId = admin.RoleId;
                newRoleMembership.UserId = vUser.UserId;
                _context.Add(newRoleMembership);
            }
            _context.SaveChanges();
```

So as long as you're running the posh commands as the same user debugging, you should never have issues with auth.

**Comment by fredbainbridge** [comment]
I am setting NOAUTH to true. I’ll stop doing that and see what happens. The unexpected character means whatever is being returned isn’t Json. This was happening when odata was first introduced and index.html was being returned instead of a script value. I’ll peak at it again later.  Thx

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ryan2065** [comment]
Ah - so that's a "feature" of blazor and I'm not quite sure how to get around it. Errors aren't sent back as normal errors, they are set as a html page since the blazor site is assuming you're not doing an API. 

I think anonymous auth was set and I was using windows auth, so a html page saying 401 was probably being sent and that's why.

**Comment by Ryan2065** [comment]
Just tried New-EAScript with WindowsAuth and it works perfectly. Nothing wrong with the cmdlet, just the user.

**Pull request merged**
